# Generated by Django 4.2.5 on 2023-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ADs",
            fields=[
                (
                    "id",
                    models.CharField(max_length=75, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
                ("image", models.ImageField(upload_to="")),
                ("visualize_status", models.BooleanField(default=True)),
            ],
        ),
    ]
